### ISSUE TITLE
How to get the download_url ?

### ISSUE THREAD

**Issue by mianor64** [Backblaze/b2-sdk-java#14]
Hi, 

From the sdk, I didn't find a way to access the download_url property, which is returned by the call to b2_authorize_account.
I noticed in B2StorageClientImpl an object accountAuthCache with this information but it's a private property. Could you please change your sdk to expose this property ? I could provide a pull request if you prefer.

Thanks

**Comment by certainmagic** [comment]
Hi mianor —

There are now methods to getDownloadByIdUrl() and getDownloadByNameUrl() on B2StorageClient. Those methods are in the tree, but not in the released jar. 

Would those meet your needs?

thanks,
ab

**Comment by mianor64** [comment]
Hi,

Does the method getDownloadByIdUrl() take a fileId in parameter? In this case, that's ok but it will be better if I can avoid doing another network call if the download base url is available somewhere in B2StorageClient.

Also, is there an equivalent to b2_get_upload_url call in the sdk ? I am defining a REST api, so I'd like to be able to generate a temporary upload URL from server side, with the sdk, and be able to use that URL from the browser to upload a file directly to Backblaze without touching my server.

Thanks

**Comment by mianor64** [comment]
Hi,

I just noticed the Webifier class that contains methods for what I need.
I am not familiar with Gradle and get errors when building the project.
Is there a Maven repository I can use to have access to the last version (1.1.1) who seemed to contain all the code I need. I am currently using the version 1.0.0 which seems the only one available from Maven central.

Thanks

**Comment by certainmagic** [comment]
Hi mianor64 --

Yes, getDownloadByIdUrl() takes a fileId.  If you want to send the base url
to a web page to do downloads more dynamically from there, I agree that it
would be best to get the base download url once and let the client make up
urls.  I will see about making those base urls available from the SDK.

Here are a few notes:

   - If you're downloading from a private bucket, be sure to use
   b2_get_download_auth instead of sending your real credentials to the client.
   - We do not yet support CORS, so your web page would need to be served
   from B2, too.   (I see from another message that you discovered this before
   I got to respond.)
   - We are actively working on adding CORS support to B2, starting with
   downloads.
   - Adding support for CORS for uploads is not yet scheduled.

The SDK does not currently expose b2_get_upload_url.  It will have to by
the time we support CORS for uploads.

thanks,
ab

**Comment by certainmagic** [comment]
Hi mianor64 --

We are planning on uploading the 1.1.1 build to maven "soon"; I need to
improve our upload process so that it's easier so that we do it more often.

It sounds from your later messages as though you're more blocked by the
lack of CORS support than by these missing methods, so I guess I won't rush
that upload.  Please let me know if I'm wrong.

**Comment by certainmagic** [comment]
I have just published v1.1.1 to both github and Maven.

**Comment by certainmagic** [comment]
this will make it into the next release.  if someone needs it sooner rather than later, please holler.
