### ISSUE TITLE
 <B2Exception 401 bad_auth_token: > how do i know what is the issue?

### ISSUE THREAD

**Issue by evnix** [Backblaze/b2-sdk-java#63]
SDK version: v2.0.0

A bit confused with all the names like bucketName/bucketId, AccountId/ApplicationKeyId/ApplicationKeyName

I have been using the keys/IDs below marked in "RED" as I am unsure if those are the ones to be used. If those aren't the right keys please let me know what are the right ones.

<img width="445" alt="Screenshot 2019-03-20 at 22 32 59" src="https://user-images.githubusercontent.com/1516273/54723806-b826b980-4b60-11e9-9ba7-b44ab6ca2f6d.png">
<img width="494" alt="Screenshot 2019-03-20 at 22 35 47" src="https://user-images.githubusercontent.com/1516273/54723815-bceb6d80-4b60-11e9-9dfa-a6bdc6a3565c.png">

my code is as follows:

```
    public String upload(String uploadFileName, File file) throws Exception {

        String random = RandomUtil.getRandomString(3);
        LocalDateTime date = LocalDateTime.now();
        B2ContentSource source = B2FileContentSource.build(file);
        String fileName = "public/"+date.getYear()+"/"
                        +date.getMonth()+"/"
                        +date.getDayOfMonth()+"/"
                        +random+"/"
                        +uploadFileName;

        B2UploadFileRequest request = B2UploadFileRequest
                .builder(bucketId /*Marked in red*/, fileName, B2ContentTypes.B2_AUTO, source)
                .setCustomField("color", "green")
                .build();

        B2FileVersion file1 = client.uploadSmallFile(request);
        log.info(file1.toString());
        return "blah-blah";
    }

    @PostConstruct
    void init(){
        client = B2StorageHttpClientBuilder.builder(accountId /*Marked in red*/,
                applicationKey /*Marked in red*/,
                "java_uploader").build();
       
    }

```

**Comment by evnix** [comment]
OK an update, It worked with something called the "master application key" but I wouldn't want to use it, I'd prefer to use the applicationKey (Id or name, whichever it is) and none seem to work.

**Comment by certainmagic** [comment]
hi evnix --

Sorry this is a little confusing.  Some people here at Backblaze are
working on clarifying it.

To authenticate with B2 you need to provide two things:
  (a) your identity
  (b) the matching secret

There are two ways to do this:

(1) One way to do that is with these:
  (a) accountId (the first red thing, which starts with 06, i think).
  (b) the master key secret
       (not shown because we generate it, give it to you, and forget it)

(2) Another way to do that is with these:
   (a) an application key id (the second red thing, which starts with
0020633)
   (b) that key's secret that we generated when you created that
application key
        (not shown because we generate it, give it to you, and forget it)

We agree that you should use an application key with restricted permissions
whenever possible, instead of the master application key.  So, we recommend
option (2) above.

In your sample, it looks like you're using the accountId and the
applicationKeyId
instead of an identity and a secret.

Does that answer your question?

thanks,
ab

**Comment by avierr** [comment]
"(b) that key's secret that we generated when you created that
application key         (not shown because we generate it, give it to you, and forget it)
"
This above should be documented more. 

It took me quite a lot of time to understand all the naming schemes used. 
I finally got it to work after a lot of permutation and combination.

The first thing , I believe people are more used to seeing ID & secret side by side. 
It would be much more simpler if backblaze kept the secret and showed it even for future use.

second thing is: confusion between bucketName or bucketId

**Comment by certainmagic** [comment]
Thanks for the feedback, avierr.  It sounds like you have things working
now.  Yay!

There will be some improvement in the terminology on the website and in the
b2-sdk-api in the short term future.  There's an open PR for some changes
to the java SDK right now.

While it would be a simpler user experience for us to hold onto secrets for
you, it is a security risk, so we don't be doing that.  Those secrets are
essentially passwords and the best practice is to never store passwords.
We only store information such as cryptographic hashes which allow us to
determine when you are providing the correct password without us keeping it.

Re: bucketName vs. bucketId.  Yes, another SDK user pointed out that it
would be useful if those were separate data types instead of both being
strings so that the compiler could help detect when arguments are swapped.
That change would have a lot of ripples for the SDK and its users so we're
not planning on making that improvement soon.

thanks,
ab

**Comment by evnix** [comment]
Thanks @certainmagic for the quick reply. 
It worked exactly as you explained! I had entered the wrong details in.
